version: '3.6'
services:
  nginx:
    image: nginx:1.15-alpine
    container_name: example-nginx
    restart: always
    volumes:
    - ./public:/var/www/public
    - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
    - 80:80
    depends_on:
    - app
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  app:
    build:
      context: .
      args:
      - COMPOSER_FLAGS=--prefer-dist --optimize-autoloader
    container_name: example-app
    restart: always
    ports:
    - 9000:9000
    environment:
    - OPCACHE_SAVE_COMMENTS=1
    - OPCACHE_VALIDATE_TIMESTAMPS=1
    - OPCACHE_REVALIDATE_FREQ=0
    volumes:
    - .:/var/www
    - ./php.ini:/usr/local/etc/php/php.ini
    - ./www.conf:/usr/local/etc/php-fpm.d/www.conf
    - ./supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
    depends_on:
    - mysql
    - redis

  schedule:
    image: ibrunotome/php:7.4
    container_name: example-schedule
    restart: always
    command: >
      bash -c "chmod +x /var/www/schedule.sh && /var/www/schedule.sh"
    environment:
    - OPCACHE_SAVE_COMMENTS=1
    - OPCACHE_VALIDATE_TIMESTAMPS=1
    - OPCACHE_REVALIDATE_FREQ=0
    volumes:
    - .:/var/www
    - ./php.ini:/usr/local/etc/php/php.ini
    depends_on:
    - mysql
    - redis

  queue:
    image: ibrunotome/php:7.4
    container_name: example-queue
    restart: always
    command: php artisan horizon
    environment:
    - OPCACHE_SAVE_COMMENTS=1
    - OPCACHE_VALIDATE_TIMESTAMPS=1
    - OPCACHE_REVALIDATE_FREQ=0
    volumes:
    - .:/var/www
    - ./php.ini:/usr/local/etc/php/php.ini
    depends_on:
    - mysql
    - redis

  mysql:
    image: mysql:5.7
    container_name: example-db
    restart: always
    volumes:
    - ./volumes/mysql:/var/lib/mysql
    ports:
    - 3306:3306
    environment:
    - MYSQL_ROOT_PASSWORD=example
    - MYSQL_DATABASE=example
    - MYSQL_USER=example
    - MYSQL_PASSWORD=example

  redis:
    image: redis:5.0.5-alpine
    container_name: example-redis
    restart: always
    ports:
    - 6379:6379
    volumes:
    - ./volumes/redis:/data
